### ISSUE TITLE
SDCC example: TimerIrqBlink translation attempt

### ISSUE THREAD

**Issue by spth** [free-pdk/fppa-code-examples#1]
SDCC is not ready yet, but I hope it will be within a few month.

A lot is already working. For the simple examples, SDCC already manages to produce mostly okayish asm (mostly correct, but not yet very efficient). I have attached an attempt to translate the TimerIrqBlink example to C code as accepted by SDCC, and the resulting asm.
There is still a bit of glue code missing (regarding the header), and there is no support for the calibration thing.

Philipp
[TimerIrqBlink.asm.gz](https://github.com/free-pdk/simple-pdk-code-examples/files/2738388/TimerIrqBlink.asm.gz)
[TimerIrqBlink.c.gz](https://github.com/free-pdk/simple-pdk-code-examples/files/2738389/TimerIrqBlink.c.gz)

**Comment by spth** [comment]
The current (revision 10862) version of the sdcc pdk branch has some more optimizations. The generated code looks much better now.

Philipp
[test.c.gz](https://github.com/free-pdk/simple-pdk-code-examples/files/2740522/test.c.gz)

**Comment by freepdk** [comment]
This is great stuff.

Maybe better move this to the new repo for SDCC examples?

**Comment by spth** [comment]
I'll complete the example and will then put it into the new repo.

Philipp
